theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://helfer-app.github.io#funktionen
  referenzen: https://helfer-app.github.io#referenzen
  demo: https://helfer-app.github.io#demo
